project:
  type: website

website:
  favicon: images/logo.png

  title: "U-KREAT"
  navbar:
    pinned: true
    logo: images/logo.png
    left:
      - href: team.qmd
        text: Meet the team
      - href: projects.qmd
        text: Projects
      - href: output.qmd
        text: Output
      - href: blog/index.qmd
        text: Blog
    right:
      - href: resources.qmd
        text: Resources
      - href: calendar.qmd
        text: Calendar
      - href: contact.qmd
        text: Contact
  back-to-top-navigation: true

  sidebar:
    - title: "Resources"
      style: "docked"
      contents:
        - resources.qmd
        - k-journals.qmd
        - g-journals.qmd
        - c-journals.qmd
        - d-journals.qmd
        - e-journals.qmd

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**NB** - this website is in active development; any information may not be final"
    type: primary
    position: below-navbar

format:
  html:
    theme: 
      light: [simplex, theme.scss]
      dark: [simplex, theme_dark.scss]
    respect-user-color-scheme: true
    toc: true



