project:
  type: website

website:
  favicon: creat_cafe.png

  title: "NE Utrecht"
  navbar:
    logo: images/creat_cafe.png
    left:
      - href: team.qmd
        text: Meet the team
      - href: projects.qmd
        text: Projects
      - href: output.qmd
        text: Output
    right:
      - href: resources.qmd
        text: Resources
      - href: contact.qmd
        text: Contact
  back-to-top-navigation: true

  sidebar:
    - title: "Resources"
      style: "docked"
      contents:
        - resources.qmd
        - journals.qmd

  announcement: 
    icon: info-circle
    dismissable: true
    content: "**NB** - this website is in active development; any information may not be final"
    type: primary
    position: below-navbar

format:
  html:
    theme: 
      light: [simplex, theme.scss]
      dark: [simplex, theme_dark.scss]
    respect-user-color-scheme: true
    toc: true



