project:
  type: website

website:
  favicon: images/logo_light.png

  title: "U-KREAT"
  navbar:
    pinned: true
    logo: images/logo_dark.png
    left:
      - href: team.qmd
        text: Meet the team
      - href: projects.qmd
        text: Projects
      - href: output.qmd
        text: Output
      - href: blog/index.qmd
        text: Blog
    right:
      - href: resources.qmd
        text: Resources
      - href: calendar.qmd
        text: Calendar
      - href: contact.qmd
        text: Contact
  back-to-top-navigation: true

  sidebar:
    - title: "Resources"
      style: "docked"
      contents:
        - resources.qmd
        - k-journals.qmd
        - g-journals.qmd
        - c-journals.qmd
        - d-journals.qmd
        - e-journals.qmd

format:
  html:
    theme: 
      light: [styles/ukreat, styles/theme.scss]
      dark: [styles/ukreat, styles/theme_dark.scss]
    respect-user-color-scheme: true
    toc: true



